### ISSUE TITLE
app crash with stack overlow

### ISSUE THREAD

**Issue by JiaLinQuan** [ShiftMediaProject/FFVS-Project-Generator#19]
I just have cloned latest ffmpeg source code (Master branch, latest commit 2fc12f4) and tried to build solution.
I am using Win10 x64 and Visual Studio Community 2015.
After building the project_generate.exe successfully, tried to run it with this command "project_generate.exe --enable-gpl --enable-version3 --disable-bzlib --disable-iconv --disable-zlib --disable-lzma --disable-sdl --toolchain=msvc".
Program says "Passing configure file..." and then crashes some minutes later

Please check this error and let me know how to fix.

Thank you.
![appcrash](https://user-images.githubusercontent.com/25911216/38883210-d9a51212-429e-11e8-9080-536a9401a459.png)

**Comment by Sibras** [comment]
Is this using a precompiled FFVS binary downloaded from this site?
The current provided binary is rather old so if you want to support anything from ffmpeg added in the 4.0 merge window (i.e. the current master) then you need a newer version compiled from git source.

A new binary is due to be released with ffmpeg 4.0 but since that has been branched recently then I will release the new version in the next day or 2.

**Comment by JiaLinQuan** [comment]
Hi, Sibras.

I have tried with ffmpeg release 3.4 and project_generate app generated solution!
Hope to get new version with ffmpeg 4.0 as well.

Thanks for your great work!!!
