### ISSUE TITLE
pthread.h not found invalid switch error

### ISSUE THREAD

**Issue by bichumon** [ShiftMediaProject/FFVS-Project-Generator#66]
ffmpeg  v0.6.1

configuration 
 --enable-nonfree --enable-gpl --enable-version3 --disable-bzlib --disable-iconv --disable-zlib --disable-lzma --disable-libx265 --disable-encoder=libx265  --disable-encoder=hevc_amf --disable-encoder=hevc_qsv --disable-decoder=hevc --disable-decoder=hevc_qsv --disable-decoder=hevc_cuvid --disable-decoder=vvc --disable-decoder=vqc --disable-encoder=hevc_mf  --disable-cuda-llvm --disable-cuvid --disable-autodetect --enable-libsrt

## Your Environment
visual studio 2019 windows 10
error 
  Generating missing DCE symbols (libavcodec)...
Invalid switch - "".
  Error: Errors detected during compilation :-
         error C1083: Cannot open include file: 'pthread.h': No such file or directory
         Based on the above error(s) there are files required for dependency libraries that are not available
         Ensure that any required dependencies are available in 'OutDir' based on the supplied configuration options before trying again.
         Consult the supplied readme for instructions for installing varying dependencies.
         If a dependency has been cloned from a ShiftMediaProject repository then ensure it has been successfully built before trying again.
           Removing the offending configuration option can also be used to remove the error.

**Comment by Sibras** [comment]
ffmpeg version 0.6.1 is from 14 years ago and predates this projects existance. Due to the changes cosntantly being made to ffmpegs build files its not possible to support every possible version going back that far. So this is very much in unsupported territory.
You can try and find a msvc compatible pthread file from somewhere and place it in the source tree and maybe that will work but its not something I can provide support for.
