### ISSUE TITLE
vcxproj files incorrectly formatted

### ISSUE THREAD

**Issue by ep1cman** [ShiftMediaProject/FFVS-Project-Generator#7]
Using the latest release the vcxproj files generated seem to be incorrectly formatted with "ItemGroup"s being placed where the xml version should go. For example in ffprobe.vcxproj:

```
<?xml versio
  <ItemGroup>
    <ClCompile Include="..\cmdutils.c" />
    <ClCompile Include="..\ffprobe.c" />
    <ClCompile Include="ffprobe\dce_defs.c" />
  </ItemGroup>n="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup Label="ProjectConfigurations">
    <ProjectConfiguration Include="DebugDLL|Win32">
      <Configuration>DebugDLL</Configuration>
```

**Comment by yunhai2009** [comment]
@ep1cman    you needs adjustment in "vcxproj" and "vcxproj.filters".you need change "<?xml versio" to "<?xml version="1.0" encoding="utf-8"?>" and find "n="1.0" encoding="utf-8"?>" and delete it,besides copy "<ItemGroup>" tag to "<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">" tag.

for example:
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
<ItemGroup>
........
</ItemGroup>
..........
</Project>

**Comment by Sibras** [comment]
Thanks for letting me know. This appears to have been an error in the appveyor CI build as versions ive compiled locally work correctly. From what I can tell appveyor must have recently changed the way they handle line endings on git checkout and it has caused this issue to occur in what was otherwise previously working code.

Ive come up with a workaround and have updated the most recent release with a recompiled version which fixes the problem.
