### ISSUE TITLE
newest binary file has problem

### ISSUE THREAD

**Issue by kpld** [ShiftMediaProject/FFVS-Project-Generator#71]
Newest binary file [FFVS-Project-Generator_1.11.10_x64.zip] could not generate ffmpeg project, it is crashed when run. But source code [Source code (tar.gz)] has no problem. I compiled source code, then it is run OK. Maybe uploaded wrong binary file.

**Comment by Sibras** [comment]
For some reason the executable compiled by the CI (which is the one uploaded to the releases) was behaving differently to the exact same code/project compiled locally. I have no idea why.
But I made some changes that seemed to have fixed whatever the issue was and they are avilable in the 1.12.0 release version.
