### ISSUE TITLE
Deleted a bunch of files on my system

### ISSUE THREAD

**Issue by Dan203** [ShiftMediaProject/FFVS-Project-Generator#9]
I ran the project generator once at a command prompt set to C:\Users\Dan just to see if it printed out a list of CLI options. It didn't. But what it did do is it deleted every single file folder in my entire user directory that started with ff or lib!!!!! 

Luckily I have a nightly disk image I could use to restore everything, but what a PITA. Perhaps you could throw up a warning before you just blindly start deleting files.

**Comment by Sibras** [comment]
This shouldn't have happened (and is a really crappy bug to encounter). I found the source of the error and it was an incorrect boolean flag that wasn't being set properly. You just happened to be the unlucky one who stumbled across it as it only occurs when there is a configure error causing the program to exit before a valid project directory had been set. The program tries to cleanup up any partially created project files in the project directory if it detects an error part way through creating them, just in this case it went a bit over board.

I have corrected the bug and also improved the detection of which files are generated by FFVS and which are not which should prevent this in the future.

**Comment by Sibras** [comment]
Also as a point of note: FFVS uses the same command line syntax as the normal ffmpeg configure script. So if you want a list of cli options you need to pass --help. Otherwise it will just attempt a configure using default arguments. 

The actual options passed back from --help will depend on the version of the ffmpeg code you are trying to compile as many are dynamically pulled from the ffmpeg source code repo being used.
